CREATE TABLE IF NOT EXISTS telegram_person
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    chat_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_telegram_person PRIMARY KEY (id)
);


ALTER TABLE telegram_person
    ADD CONSTRAINT uc_telegram_person_username UNIQUE (username);

CREATE TABLE IF NOT EXISTS auth_token
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token     VARCHAR(255),
    person_id BIGINT,
    CONSTRAINT pk_auth_token PRIMARY KEY (id)
);

ALTER TABLE auth_token
    ADD CONSTRAINT FK_AUTH_TOKEN_ON_PERSON FOREIGN KEY (person_id) REFERENCES telegram_person (id);
